CurrencyRatesApp/Controllers/HomeController.cs
using CurrencyRatesApp.Rates;
using System.Collections.Generic;
using System.Web.Mvc;

namespace CurrencyRatesApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetRates()
        {
            var rates = new RatesProvider().Get(new List<string>() { "USD", "EUR" });

            return Json(rates, JsonRequestBehavior.AllowGet);
        }
    }
}

CurrencyRatesApp/Controllers/RatesController.cs
using CurrencyRatesApp.Rates;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace CurrencyRatesApp.Controllers
{
    public class RatesController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> GetRates()
        {
            var provider = new RatesProvider();
            var rates = await provider.Get(new List<string>() { "USD", "EUR" });

            return Json(rates, JsonRequestBehavior.AllowGet);
        }
    }
}

CurrencyRatesApp/Views/Rates/Index.cshtml
@{
    ViewBag.Title = "Currency Rates App";
}

    <div class="row">
        <div class="col-md-12">
   
            <h3>Currency Rates - www.forex.se</h3>
            <p>Please click load button to fetch currencies</p>
            <button class="btn btn-primary" data-bind="click: loadRates">Load</button>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <table data-bind="if: Rates().length > 0"class="table">
                <thead>
                    <tr>
                        <th>Code</th>
                        <th>Buy</th>
                        <th>Sell</th>
                    </tr>
                </thead>
                <tbody data-bind="foreach: Rates">
                    <tr>
                        <td data-bind="text: Code"> </td>
                        <td data-bind="text: Buy"> </td>
                        <td data-bind="text: Sell"> </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

CurrencyRatesApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Currency Rates", "Index", "Rates", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Currency Rates</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")
    @Scripts.Render("~/bundles/app")

    @RenderSection("scripts", required: false)
</body>
</html>